version: '3.7'

services:

    # SSH Honeypot Service
    ssh_honeypot:
        container_name: ssh_honeypot
        build:
          context: .
          dockerfile: Dockerfile
        image: basic_ssh_honeypot
        tty: true  
        command: python ssh_honeypot.py --bind 0.0.0.0 --port 2222
        volumes:
            - .:/usr/src/app
        env_file:
            - ./.env
        ports:
            - 22:2222
        environment:
            - CHOKIDAR_USEPOLLING=true
            
    # SSH Honeypot Downloader Service
    ssh_honeypot_downloader:
        container_name: ssh_honeypot_downloader
        build:
          context: .
          dockerfile: Dockerfile
        image: ssh_honeypot_downloader
        tty: true  
        volumes:
            - .:/usr/src/app
        env_file:
            - ./.env
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - "ssh_honeypot_redis_db"
        # Wait for Redis to be ready before executing the command
        command: ["./wait-for-it.sh", "ssh_honeypot_redis_db:6379", "--", "python", "ssh_honeypot_downloader.py"]
            
    # Redis Database for SSH Honeypot
    ssh_honeypot_redis_db:
        container_name: ssh_honeypot_redis_db
        image: redis:6.0.7-alpine
        command: redis-server --requirepass password 
        env_file:
            - ./.env
